package com.derfence.astroface.wear.astro

internal data class ConstellationCatalog(
    val stars: List<ConstellationStar>,
    val segments: List<ConstellationSegment>
)

internal data class ConstellationStar(
    val id: String,
    val raHours: Double,
    val decDegrees: Double
)

internal data class ConstellationSegment(
    val constellationId: String,
    val fromStarId: String,
    val toStarId: String
)

internal object DefaultConstellationCatalog {
    val value = ConstellationCatalog(
        stars = listOf(
            star("aldebaran", 4.598, 16.51),
            star("albireo", 19.512, 27.96),
            star("alderamin", 21.309, 62.59),
            star("alfirk", 21.477, 70.56),
            star("algieba", 10.333, 19.84),
            star("algenib", 0.221, 15.18),
            star("algol", 3.137, 40.96),
            star("alhena", 6.628, 16.40),
            star("alioth", 12.900, 55.96),
            star("alkaid", 13.792, 49.31),
            star("almach", 2.065, 42.33),
            star("alnilam", 5.604, -1.20),
            star("alnitak", 5.679, -1.94),
            star("alpheratz", 0.139, 29.09),
            star("alphecca", 15.579, 26.71),
            star("alshain", 19.921, 6.41),
            star("altair", 19.846, 8.87),
            star("antares", 16.490, -26.43),
            star("arcturus", 14.261, 19.18),
            star("atik", 3.902, 31.88),
            star("bellatrix", 5.418, 6.35),
            star("betelgeuse", 5.919, 7.41),
            star("caph", 0.153, 59.15),
            star("capella", 5.279, 46.00),
            star("castor", 7.576, 31.89),
            star("chertan", 11.237, 15.43),
            star("deneb", 20.691, 45.28),
            star("denebola", 11.817, 14.57),
            star("delta_and", 0.655, 30.86),
            star("delta_cep", 22.486, 58.42),
            star("delta_crb", 15.827, 26.07),
            star("delta_cyg", 19.750, 45.13),
            star("delta_her", 17.250, 24.84),
            star("delta_per", 3.715, 47.79),
            star("dubhe", 11.062, 61.75),
            star("edasich", 15.416, 58.97),
            star("elnath", 5.438, 28.61),
            star("epsilon_crb", 15.960, 26.88),
            star("epsilon_per", 3.964, 40.01),
            star("errai", 23.655, 77.63),
            star("etamin", 17.944, 51.49),
            star("gienah_cyg", 20.771, 33.97),
            star("grumium", 17.535, 55.18),
            star("hassaleh", 4.950, 33.17),
            star("hyadum_i", 4.329, 15.63),
            star("izar", 14.749, 27.07),
            star("kaus_australis", 18.402, -34.38),
            star("kaus_borealis", 18.466, -25.42),
            star("kaus_media", 18.350, -29.83),
            star("kornephoros", 16.503, 21.49),
            star("kuma", 17.147, 65.71),
            star("mahasim", 5.995, 37.21),
            star("markab", 23.079, 15.21),
            star("mebsuta", 6.732, 25.13),
            star("megrez", 12.257, 57.03),
            star("mekbuda", 7.068, 20.57),
            star("menkalinan", 5.992, 44.95),
            star("merak", 11.030, 56.38),
            star("mintaka", 5.533, -0.30),
            star("mirach", 1.163, 35.62),
            star("mirfak", 3.405, 49.86),
            star("mizar", 13.398, 54.93),
            star("muphrid", 13.911, 18.40),
            star("nekkar", 15.032, 40.39),
            star("nunki", 18.921, -26.30),
            star("nusakan", 15.464, 29.11),
            star("phecda", 11.897, 53.69),
            star("pi_her", 17.251, 36.81),
            star("pollux", 7.755, 28.03),
            star("rasalgethi", 17.245, 14.39),
            star("rasalas", 9.879, 26.01),
            star("rastaban", 17.507, 52.30),
            star("regulus", 10.139, 11.97),
            star("rigel", 5.242, -8.20),
            star("ruchbah", 1.430, 60.24),
            star("sadr", 20.371, 40.26),
            star("saiph", 5.795, -9.67),
            star("scheat", 23.063, 28.08),
            star("schedar", 0.675, 56.54),
            star("seginus", 14.535, 38.31),
            star("segin_cas", 1.906, 63.67),
            star("sheliak", 18.835, 33.36),
            star("sirius", 6.752, -16.72),
            star("spica", 13.420, -11.16),
            star("sulafat", 18.982, 32.69),
            star("tarazed", 19.771, 10.61),
            star("theta2_tauri", 4.477, 15.87),
            star("theta_aql", 20.188, -0.82),
            star("thuban", 14.074, 64.38),
            star("vega", 18.615, 38.78),
            star("vindemiatrix", 13.037, 10.96),
            star("wasat", 7.335, 21.98),
            star("zaniah", 12.331, -0.67),
            star("zavijava", 11.845, 1.76),
            star("zeta_cep", 22.181, 58.20),
            star("zeta_her", 16.688, 31.60),
            star("zeta_lyr", 18.746, 37.61),
            star("zeta_tau", 5.627, 21.14),
            star("zosma", 11.235, 20.52)
        ),
        segments = listOf(
            segment("Ursa Major", "dubhe", "merak"),
            segment("Ursa Major", "merak", "phecda"),
            segment("Ursa Major", "phecda", "megrez"),
            segment("Ursa Major", "megrez", "dubhe"),
            segment("Ursa Major", "megrez", "alioth"),
            segment("Ursa Major", "alioth", "mizar"),
            segment("Ursa Major", "mizar", "alkaid"),
            segment("Cassiopeia", "caph", "schedar"),
            segment("Cassiopeia", "schedar", "ruchbah"),
            segment("Cassiopeia", "ruchbah", "segin_cas"),
            segment("Cygnus", "deneb", "sadr"),
            segment("Cygnus", "sadr", "gienah_cyg"),
            segment("Cygnus", "sadr", "delta_cyg"),
            segment("Cygnus", "sadr", "albireo"),
            segment("Lyra", "vega", "zeta_lyr"),
            segment("Lyra", "zeta_lyr", "sheliak"),
            segment("Lyra", "sheliak", "sulafat"),
            segment("Lyra", "sulafat", "zeta_lyr"),
            segment("Aquila", "tarazed", "altair"),
            segment("Aquila", "altair", "alshain"),
            segment("Aquila", "altair", "theta_aql"),
            segment("Pegasus", "markab", "scheat"),
            segment("Pegasus", "scheat", "alpheratz"),
            segment("Pegasus", "alpheratz", "algenib"),
            segment("Pegasus", "algenib", "markab"),
            segment("Andromeda", "alpheratz", "delta_and"),
            segment("Andromeda", "delta_and", "mirach"),
            segment("Andromeda", "mirach", "almach"),
            segment("Perseus", "mirfak", "delta_per"),
            segment("Perseus", "delta_per", "epsilon_per"),
            segment("Perseus", "epsilon_per", "atik"),
            segment("Perseus", "mirfak", "algol"),
            segment("Auriga", "capella", "menkalinan"),
            segment("Auriga", "menkalinan", "mahasim"),
            segment("Auriga", "mahasim", "elnath"),
            segment("Auriga", "elnath", "hassaleh"),
            segment("Auriga", "hassaleh", "capella"),
            segment("Gemini", "castor", "mebsuta"),
            segment("Gemini", "mebsuta", "mekbuda"),
            segment("Gemini", "mekbuda", "alhena"),
            segment("Gemini", "pollux", "wasat"),
            segment("Gemini", "wasat", "alhena"),
            segment("Orion", "betelgeuse", "bellatrix"),
            segment("Orion", "bellatrix", "mintaka"),
            segment("Orion", "mintaka", "alnilam"),
            segment("Orion", "alnilam", "alnitak"),
            segment("Orion", "alnitak", "saiph"),
            segment("Orion", "saiph", "rigel"),
            segment("Orion", "rigel", "bellatrix"),
            segment("Orion", "betelgeuse", "alnitak"),
            segment("Taurus", "aldebaran", "hyadum_i"),
            segment("Taurus", "hyadum_i", "theta2_tauri"),
            segment("Taurus", "theta2_tauri", "zeta_tau"),
            segment("Taurus", "aldebaran", "elnath"),
            segment("Leo", "regulus", "algieba"),
            segment("Leo", "algieba", "rasalas"),
            segment("Leo", "algieba", "zosma"),
            segment("Leo", "zosma", "denebola"),
            segment("Leo", "denebola", "chertan"),
            segment("Leo", "chertan", "regulus"),
            segment("Bootes", "arcturus", "izar"),
            segment("Bootes", "izar", "nekkar"),
            segment("Bootes", "nekkar", "seginus"),
            segment("Bootes", "seginus", "izar"),
            segment("Bootes", "izar", "muphrid"),
            segment("Bootes", "muphrid", "arcturus"),
            segment("Corona Borealis", "nusakan", "alphecca"),
            segment("Corona Borealis", "alphecca", "delta_crb"),
            segment("Corona Borealis", "delta_crb", "epsilon_crb"),
            segment("Hercules", "kornephoros", "zeta_her"),
            segment("Hercules", "zeta_her", "pi_her"),
            segment("Hercules", "pi_her", "delta_her"),
            segment("Hercules", "delta_her", "kornephoros"),
            segment("Hercules", "delta_her", "rasalgethi"),
            segment("Draco", "etamin", "rastaban"),
            segment("Draco", "rastaban", "grumium"),
            segment("Draco", "grumium", "kuma"),
            segment("Draco", "kuma", "thuban"),
            segment("Draco", "thuban", "edasich"),
            segment("Cepheus", "alderamin", "zeta_cep"),
            segment("Cepheus", "zeta_cep", "delta_cep"),
            segment("Cepheus", "delta_cep", "alfirk"),
            segment("Cepheus", "alfirk", "errai"),
            segment("Cepheus", "errai", "alderamin"),
            segment("Virgo", "spica", "zaniah"),
            segment("Virgo", "zaniah", "zavijava"),
            segment("Virgo", "zaniah", "vindemiatrix"),
            segment("Sagittarius", "kaus_australis", "kaus_media"),
            segment("Sagittarius", "kaus_media", "kaus_borealis"),
            segment("Sagittarius", "kaus_borealis", "nunki")
        )
    )

    private fun star(id: String, raHours: Double, decDegrees: Double): ConstellationStar =
        ConstellationStar(id, raHours, decDegrees)

    private fun segment(
        constellationId: String,
        fromStarId: String,
        toStarId: String
    ): ConstellationSegment =
        ConstellationSegment(constellationId, fromStarId, toStarId)
}
